#!/bin/bash
set -e

MID_HOME="/opt/agent"
CONF_FILE="${MID_HOME}/config.xml"
CONF_FILE_ORIGIN="/opt/config.xml"

# Mandatory ENV
SN_URL=${SN_URL:-}
SN_USER=${SN_USER:-}
SN_PASSWD=${SN_PASSWD:-}
SN_MID_NAME=${SN_MID_NAME:-}

#generate random uuid
APPEND_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 12 | head -n 1)

#combine sn_mid_name and uuid
SN_MID_NAME_UNIQUE="$SN_MID_NAME-$APPEND_UUID"

checkConf () {
  if [ ! -e $CONF_FILE ]
    then
      cp $CONF_FILE_ORIGIN $CONF_FILE
      generateConf
  fi
}

generateConf () {
  # Setup config
  /opt/fill-config-parameter $CONF_FILE name ${SN_MID_NAME_UNIQUE}
  /opt/fill-config-parameter $CONF_FILE mid.instance.username ${SN_USER}
  /opt/fill-config-parameter $CONF_FILE mid.instance.password ${SN_PASSWD}
  /opt/fill-config-parameter $CONF_FILE url ${SN_URL}
}

midStart () {
  checkConf
  # start supervisord
  echo "Starting supervisord..."
  exec /usr/bin/supervisord -c /opt/supervisord.conf
}

midSetup () {
  checkConf
  cat $CONF_FILE
  echo ""
}

midHelp () {
  echo "Available options:"
  echo " mid:start          - Starts the mid server (default)"
  echo " mid:setup          - Generate config.xml"
  echo " mid:help           - Displays the help"
  echo " [command]          - Execute the specified linux command eg. bash."
}

case "$1" in
  mid:start)
    midStart
    ;;
  mid:setup)
    midSetup
    ;;
  mid:help)
    midHelp
    ;;
  *)
    if [ -x $1 ]; then
      $1
    else
      prog=$(which $1)
      if [ -n "${prog}" ] ; then
        shift 1
        $prog $@
      else
        midHelp
      fi
    fi
    ;;
esac

exit 0
